In [1]:
import tensorflow as tf

In [2]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [3]:
tf.constant([[1,2,3],
             [1,2,3]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [4]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [7]:
tf.random.normal((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1156448 , -0.62507373, -0.5981605 ],
       [-2.566133  , -0.64895356,  0.27796268],
       [-0.8523964 , -0.22502908, -1.0913514 ]], dtype=float32)>

In [8]:
tf.random.uniform((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.8044375 , 0.47680616, 0.05447996],
       [0.8886324 , 0.2528597 , 0.14465177]], dtype=float32)>

In [9]:
tf.range(start=1,limit=10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [10]:
x=tf.range(start=1,limit=10,delta=2)
tf.cast(x,dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [11]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

In [12]:
x+y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [13]:
z=tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [14]:
x-y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [15]:
x/y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [16]:
x*y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [17]:
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [18]:
tf.reduce_sum(x*y)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [19]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))

In [20]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.21087   ,  0.6823341 ,  0.6068389 ,  1.9848208 ],
       [ 1.7777061 , -0.91488826,  0.8237328 , -0.74078006]],
      dtype=float32)>

In [21]:
x@y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.21087   ,  0.6823341 ,  0.6068389 ,  1.9848208 ],
       [ 1.7777061 , -0.91488826,  0.8237328 , -0.74078006]],
      dtype=float32)>

In [22]:
x=tf.range(9)

In [23]:
x=tf.reshape(x,(3,3))

In [24]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [25]:
tf.transpose(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [26]:
# Neural Network

# Neural Network

In [27]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [28]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [29]:
x_train.shape

(60000, 28, 28)

In [30]:
x_train=x_train.reshape(-1,28*28).astype("float32")/255
x_train.shape

(60000, 784)

In [31]:
x_test=x_test.reshape(-1,28*28).astype("float32")/255

In [32]:
model=keras.Sequential(
    [
     keras.Input(shape=(28*28)),
     layers.Dense(512,activation="relu"),
     layers.Dense(256,activation="relu"),
     layers.Dense(10)
     
    ]
)

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [35]:
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)

Epoch 1/5
1875/1875 - 10s - loss: 0.1846 - accuracy: 0.9436 - 10s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 6s - loss: 0.0806 - accuracy: 0.9755 - 6s/epoch - 3ms/step
Epoch 3/5
1875/1875 - 6s - loss: 0.0569 - accuracy: 0.9822 - 6s/epoch - 3ms/step
Epoch 4/5
1875/1875 - 4s - loss: 0.0384 - accuracy: 0.9880 - 4s/epoch - 2ms/step
Epoch 5/5
1875/1875 - 4s - loss: 0.0341 - accuracy: 0.9894 - 4s/epoch - 2ms/step


In [36]:
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

313/313 - 1s - loss: 0.0810 - accuracy: 0.9788 - 923ms/epoch - 3ms/step


[0.08103226125240326, 0.9787999987602234]

In [37]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


## or

In [38]:
model=keras.Sequential()
model.add(layers.Input(shape=(28*28)))
model.add(layers.Dense(512,activation='relu'))
model.add(layers.Dense(256,activation='relu'))
model.add(layers.Dense(128,activation='relu'))
model.add(layers.Dense(10))

In [39]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [40]:
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)


Epoch 1/5
1875/1875 - 5s - loss: 0.1960 - accuracy: 0.9420 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 5s - loss: 0.0873 - accuracy: 0.9736 - 5s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 5s - loss: 0.0614 - accuracy: 0.9811 - 5s/epoch - 3ms/step
Epoch 4/5
1875/1875 - 5s - loss: 0.0472 - accuracy: 0.9848 - 5s/epoch - 3ms/step
Epoch 5/5
1875/1875 - 5s - loss: 0.0388 - accuracy: 0.9877 - 5s/epoch - 3ms/step


In [ ]:
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

In [ ]:
#Functional API

# Functional API

In [ ]:
inputs=keras.Input(shape=(784))
hidden=layers.Dense(512, activation="relu")(inputs)
hidden=layers.Dense(256, activation="relu")(hidden)
output=layers.Dense(10,activation='softmax')(hidden)
model= keras.Model(inputs=inputs,outputs=output)

In [ ]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"]
)

In [45]:
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)

1875/1875 - 5s - loss: 0.1854 - accuracy: 0.9431 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.0803 - accuracy: 0.9754 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 4s - loss: 0.0533 - accuracy: 0.9830 - 4s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 4s - loss: 0.0402 - accuracy: 0.9876 - 4s/epoch - 2ms/step
Epoch 5/5
1875/1875 - 4s - loss: 0.0342 - accuracy: 0.9887 - 4s/epoch - 2ms/step


In [46]:
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

313/313 - 1s - loss: 0.0639 - accuracy: 0.9810 - 845ms/epoch - 3ms/step


[0.0639151930809021, 0.9810000061988831]

In [47]:
#convolution

# COnvolutional neural network

In [48]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers 
from tensorflow.keras.datasets import cifar10

In [49]:
# confirms the gpu
#physical_devices=tf.config.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(physical_devices[0],True)

In [50]:
(x_train,y_train),(x_test,y_test)=cifar10.load_data()

170508288/170498071 [==============================] - 6s 0us/step


In [51]:
x_train.shape

(50000, 32, 32, 3)

In [52]:
x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255

In [53]:
model=keras.Sequential(
    [
     keras.layers.InputLayer(input_shape=(32,32,3)),
     layers.Conv2D(32,(3,3),padding='valid',activation='relu'),
     layers.MaxPool2D(pool_size=(2,2)),
     layers.Conv2D(64,3,activation='relu'),
     layers.MaxPool2D(),
     layers.Conv2D(128,3,activation='relu'),
     layers.Flatten(),
     layers.Dense(64,activation='relu'),
     layers.Dense(10)
    ]
)

In [54]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"]
)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [55]:
model.fit(x_train,y_train,batch_size=64,epochs=10,verbose=2)

Epoch 1/10
782/782 - 13s - loss: 1.6757 - accuracy: 0.3882 - 13s/epoch - 16ms/step
Epoch 2/10
782/782 - 5s - loss: 1.3281 - accuracy: 0.5273 - 5s/epoch - 7ms/step
Epoch 3/10
782/782 - 5s - loss: 1.2039 - accuracy: 0.5767 - 5s/epoch - 7ms/step
Epoch 4/10
782/782 - 5s - loss: 1.1071 - accuracy: 0.6125 - 5s/epoch - 7ms/step
Epoch 5/10
782/782 - 5s - loss: 1.0224 - accuracy: 0.6446 - 5s/epoch - 7ms/step
Epoch 6/10
782/782 - 5s - loss: 0.9604 - accuracy: 0.6670 - 5s/epoch - 7ms/step
Epoch 7/10
782/782 - 5s - loss: 0.9143 - accuracy: 0.6840 - 5s/epoch - 7ms/step
Epoch 8/10
782/782 - 5s - loss: 0.8624 - accuracy: 0.7024 - 5s/epoch - 7ms/step
Epoch 9/10
782/782 - 5s - loss: 0.8238 - accuracy: 0.7152 - 5s/epoch - 7ms/step
Epoch 10/10
782/782 - 5s - loss: 0.7855 - accuracy: 0.7289 - 5s/epoch - 7ms/step


In [56]:
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

313/313 - 1s - loss: 0.8716 - accuracy: 0.7012 - 1s/epoch - 4ms/step


[0.8715869188308716, 0.701200008392334]

In [57]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 4, 4, 128)         73856     
                                                                 
 flatten (Flatten)           (None, 2048)             

In [58]:
def mymodel():
   input = keras.Input(shape=(32,32,3))
   h1=layers.Conv2D(32,3)(input)
   h1=layers.BatchNormalization()(h1)
   h1=keras.activations.relu(h1)
   h2=layers.MaxPool2D()(h1)
   h3=layers.Conv2D(64,5,padding='same')(h2)
   h3=layers.BatchNormalization()(h3)
   h3=keras.activations.relu(h3)
   h3=layers.Conv2D(128,5,padding='same')(h3)
   h3=layers.BatchNormalization()(h3)
   h3=keras.activations.relu(h3)
   h3=layers.Flatten()(h3)
   h4=layers.Dense(64,activation='relu')(h3)
   output=layers.Dense(10)(h4)
   model=keras.Model(inputs=input,outputs=output)

   return model

In [59]:
model=mymodel()
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=["accuracy"]
)

In [60]:
model.fit(x_train,y_train,batch_size=64,epochs=10,verbose=2)

Epoch 1/10
782/782 - 13s - loss: 1.4123 - accuracy: 0.5072 - 13s/epoch - 17ms/step
Epoch 2/10
782/782 - 12s - loss: 0.9226 - accuracy: 0.6785 - 12s/epoch - 15ms/step
Epoch 3/10
782/782 - 12s - loss: 0.7329 - accuracy: 0.7454 - 12s/epoch - 15ms/step
Epoch 4/10
782/782 - 12s - loss: 0.6165 - accuracy: 0.7852 - 12s/epoch - 15ms/step
Epoch 5/10
782/782 - 12s - loss: 0.5141 - accuracy: 0.8222 - 12s/epoch - 15ms/step
Epoch 6/10
782/782 - 12s - loss: 0.4404 - accuracy: 0.8468 - 12s/epoch - 15ms/step
Epoch 7/10
782/782 - 12s - loss: 0.3649 - accuracy: 0.8741 - 12s/epoch - 15ms/step
Epoch 8/10
782/782 - 12s - loss: 0.2968 - accuracy: 0.8983 - 12s/epoch - 15ms/step
Epoch 9/10
782/782 - 12s - loss: 0.2363 - accuracy: 0.9211 - 12s/epoch - 16ms/step
Epoch 10/10
782/782 - 12s - loss: 0.1979 - accuracy: 0.9345 - 12s/epoch - 16ms/step


In [61]:
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

313/313 - 2s - loss: 1.0934 - accuracy: 0.6890 - 2s/epoch - 6ms/step


[1.093356966972351, 0.6890000104904175]

In [62]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 32, 32, 3)]       0         
                                                                 
 conv2d_3 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 batch_normalization (BatchN  (None, 30, 30, 32)       128       
 ormalization)                                                   
                                                                 
 tf.nn.relu (TFOpLambda)     (None, 30, 30, 32)        0         
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 15, 15, 64)        5126

## Regularisations

In [63]:
from tensorflow.keras import regularizers

def mymodel():
   input = keras.Input(shape=(32,32,3))
   h1=layers.Conv2D(32,3,
                    padding="same",
                    kernel_regularizer=regularizers.l2(0.01)
                    )(input)
   h1=layers.BatchNormalization()(h1)
   h1=keras.activations.relu(h1)
   h2=layers.MaxPool2D()(h1)
   h3=layers.Conv2D(64,5,padding='same',
                    kernel_regularizer=regularizers.l2(0.01))(h2)
   h3=layers.BatchNormalization()(h3)
   h3=keras.activations.relu(h3)
   h3=layers.MaxPool2D()(h3)
   h3=layers.Conv2D(128,5,padding='same',
                    kernel_regularizer=regularizers.l2(0.01))(h3)
   h3=layers.BatchNormalization()(h3)
   h3=keras.activations.relu(h3)
   h3=layers.Flatten()(h3)
   h4=layers.Dense(64,activation='relu',
                   kernel_regularizer=regularizers.l2(0.01))(h3)
   h4=layers.Dropout(0.5)(h4)
   output=layers.Dense(10)(h4)
   model=keras.Model(inputs=input,outputs=output)

   return model

In [64]:
model=mymodel()
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=["accuracy"]
)
model.fit(x_train,y_train,batch_size=64,epochs=10,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Epoch 1/10
782/782 - 10s - loss: 2.9615 - accuracy: 0.3149 - 10s/epoch - 13ms/step
Epoch 2/10
782/782 - 9s - loss: 1.8388 - accuracy: 0.4384 - 9s/epoch - 11ms/step
Epoch 3/10
782/782 - 8s - loss: 1.6293 - accuracy: 0.4817 - 8s/epoch - 11ms/step
Epoch 4/10
782/782 - 8s - loss: 1.5405 - accuracy: 0.5072 - 8s/epoch - 11ms/step
Epoch 5/10
782/782 - 9s - loss: 1.4835 - accuracy: 0.5323 - 9s/epoch - 11ms/step
Epoch 6/10
782/782 - 8s - loss: 1.4445 - accuracy: 0.5487 - 8s/epoch - 11ms/step
Epoch 7/10
782/782 - 9s - loss: 1.4185 - accuracy: 0.5605 - 9s/epoch - 11ms/step
Epoch 8/10
782/782 - 9s - loss: 1.3932 - accuracy: 0.5718 - 9s/epoch - 11ms/step
Epoch 9/10
782/782 - 9s - loss: 1.3849 - accuracy: 0.5772 - 9s/epoch - 11ms/step
Epoch 10/10
782/782 - 9s - loss: 1.3531 - accuracy: 0.5918 - 9s/epoch - 11ms/step
313/313 - 2s - loss: 1.5122 - accuracy: 0.5598 - 2s/epoch - 5ms/step


[1.5122478008270264, 0.5598000288009644]